cc_library(
    name = "util",
    hdrs = ["util.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "perf_util",
    hdrs = ["perf_util.h"],
    srcs = ["perf_util.cc"],
    visibility = ["//visibility:public"],
)